### ISSUE TITLE
docker version timeout

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/subway#43]
## Reproduce
first start a local mandala node
```
docker run -it --rm -p 9944:9944 -p 9933:9933 ghcr.io/acalanetwork/mandala-node:sha-104e277 --dev --ws-external --rpc-port=9933 --rpc-external --rpc-cors=all --rpc-methods=unsafe -levm=debug --pruning=archive --instant-sealing
```

start a normal subway on port 9955
```
ENDPOINTS=ws://localhost:9944 PORT=9955 cargo run
```

open polkadotjs https://polkadot.js.org/apps/?rpc=ws%3A%2F%2Flocalhost%3A9955#/explorer, **everything works fine**.

then close normal subway, start a docker version instead
```
docker run \
  -e ENDPOINTS=ws://localhost:9944 \
  -e PORT=9955 \
  -p 9955:9955 \
  acala/subway:sha-7c1610c
```

open (or refresh) polkadotjs https://polkadot.js.org/apps/?rpc=ws%3A%2F%2Flocalhost%3A9955#/explorer, and app won't load with timeout error

<img width="729" alt="Screenshot 2023-03-09 at 14 55 22" src="https://user-images.githubusercontent.com/16548786/223944169-1d8ae543-1c24-4762-bb30-cb36a871ef89.png">

**Comment by shunjizhan** [comment]
I suspect it might have something to do with 80 port, since if we change to `ENDPOINTS=wss://acala-rpc.dwellir.com`, same issue still happens. Changing it to `ENDPOINTS=wss://acala-rpc.dwellir.com:443` makes it work.  However we can't add 443 to localhost

**Comment by shunjizhan** [comment]
> ENDPOINTS=ws://host.docker.internal:9944
oh right that's a nice catch! 

Curious why `ENDPOINTS=wss://acala-rpc.dwellir.com` doesn't work either

**Comment by ermalkaleci** [comment]
I think the port is required
