### ISSUE TITLE
pass through dev rpcs

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/subway#44]
would it be possible to expose dev rpc calls such as `api.rpc.engine.createBlock`? 

Although it's not required for prod, it would be super convenient for 1-click subway substitution for e2e tests. For example I have a bunch of e2e tests like
```
tests => eth-rpc-adapter => local mandala
```
and I can directly test subway compatibility with these e2e tests by doing
```
tests => eth-rpc-adapter => subway =>  local mandala
```

**Comment by shunjizhan** [comment]
currently I can still do it by modifying tests to call dev rpcs directly on mandala, but that's not very convenient, since I have a "reverse" these changes if I want to test without subway again, and in tests I will need to keep track of two endpoints

**Comment by xlc** [comment]
Just create you own config file and add dev rpc there

https://github.com/AcalaNetwork/subway/blob/7c1610c13bb1e467011b9284b7f11dcfafc7204e/config.yml#L14

**Comment by shunjizhan** [comment]
is there anyway I can override it when running docker version?

**Comment by xlc** [comment]
you can build your own docker image, with the new config file, and use it
