### ISSUE TITLE
validate subcommand to validate config

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/subway#55]
A new subcommand `validate` that validate config and try to connect to all endpoints and make sure they are all good.

Example usage: `subway validate --config config.yml`
It should check if the config file is valid, and connect to each endpoint, and report the connection status.
Should exit with 1 if anything failed.

**Comment by leanceaner** [comment]
After successful `validate`, the subway server will continue to start or process exit directly?

**Comment by xlc** [comment]
it should exit with code 0 so that CI can use it to validate config files.
